#!/bin/sh
#
# For each gem in the list, run the command "gem pristine".
#
# In some debugging cases this script is preferable to running "gem pristine --all"
# because this script prints each gem's name before the gem's restore is attempted,
# and if any gem fails to restore, this script will continue with subsequent gems.
#
# Before we run this, we typically remove any old versions of gems:
#   gem cleanup

gem list | awk '{print $1}' | while read gem_name; do echo "Restoring $gem_name..."; gem pristine $gem_name; done
