#!/bin/bash

name=${PWD##*/}
echo "name: $name"

function dash_d { [ -d $1 ] || echo "need a directory: $1"; }
function dash_f { [ -f $1 ] || echo "need a file: $1"; }

dash_d coverage
dash_f coverage/jquery-1.3.2.min.js
dash_f coverage/index.html
dash_f coverage/jquery.tablesorter.min.js
dash_f coverage/rcov.js
dash_f coverage/screen.css
dash_f coverage/lib-${name}_rb.html
dash_d doc
dash_d doc/css
dash_d doc/js
dash_d doc/REXML
dash_f doc/class_list.html
dash_f doc/file_list.html
dash_f doc/file.README.html
dash_d lib
dash_d lib/$name
dash_f lib/$name.rb
dash_f LICENSE.txt
dash_f README.rdoc
dash_f $name.gemspec
dash_f $name.sha512.txt
dash_d test
dash_d test/$name
dash_f test/$name.rb
