#!/bin/sh
#
# Ruby gem install using all possible ways we know
# to ensure a clean install:
#
#  - uninstall any other gems with the same name
#  - remove all versions of this gem from the caches
#  - install with these flags: --test --no-user-install --trust-policy HighSecurity

gem uninstall $1 --all --ignore-dependencies 
gem-cache-cleaner $1
gem install $1 --test --no-user-install --trust-policy HighSecurity


