#!/bin/bash

gem_name=`gemspec-name`
gem_name_version=`gemspec-name-version`

echo $gem_name
for path in .git INSTALL.txt LICENSE.txt README.rdoc coverage doc lib test $gem_name.gemspec $gem_name-*.gem $gem_name.sha512.txt
do
  echo "testing $path"
  [[ -e $path ]] || echo "-e $path"
done
