#!/bin/sh
set -o errexit

##
# Publish our gem to github.
#
# This does three things:
#   1. adds all the files in the current repo.
#   2. Commits with a message.
#   3. Pushes to github.
#
# Example:
#   cd mygem
#   gemforge-publish-to-github "Your Commit Message Here"
##

git add *
git commit -am "$1" 
git push origin master

