#!/bin/sh
set -o errexit

##
# Run our gem's tests, when we're in our gem's directory.
#
# Example:
#   cd mygem
#   gemforge-test
#   => runs ruby tests and reports any errors
##

ruby -rubygems -Ilib -Itest test/*.rb
