#!/bin/sh
set -o errexit

##
# Uninstall older versions of all of our Ruby gems.
#
# This script creates a list of commands that you can then edit or run.
# We do it this way because it's safer than running the commands as is.
#
# Example:
#   cd ~sixarm/github/
#   gemforge-uninstall-older-versions-generator
#   => list of commands to run to uninstall all our gems
##

ls -1 */*gem | sed 's#.*/#gem uninstall #; s#.gem#"#; s#-# --version "< #'
