#!/bin/sh
set -o errexit

##
# Publish our gem to our local host, 
# tpyically our own sixarm.com website.
#
# Example:
#   cd mygem
#   gemforge-publish-to-local-host
#   => copies all the gem's files to our local host
##

# Get the current directory's gem info
gem_name=`gemspec-cat | gemspec-to-gem-name`
gem_name_version=`gemspec-cat | gemspec-to-gem-name-version`

# Where on the local host to put the gem directory
gem_generate_directory=/var/www/sixarm/html

# Make the gem's directory, if needed
mkdir -p $gem_generate_directory/gems/$gem_name

# Sync all the gem files
rsync --recursive -C --hard-links --exclude='.git/' --executability --delete --times * $gem_generate_directory/gems/$gem_name/

# Also, put the actual gem file one directory higher, so it can be built
rsync *.gem $gem_generate_directory/gems/

# Generate
gem generate --backtrace --directory=$gem_generate_directory/

