#!/bin/sh
set -o errexit

##
# Remove old files from our gem's directory.
# This is in preparation for building a gem.
##

# Remove any existing version of our gem
rm -f *.gem

# Remove any existing checksums of our gem
rm -f *sha512.txt

# Remove all old temp files
find . | grep ".*~" | xargs rm -f "*~"
