#!/bin/sh
set -o errexit

##
# Given a gemspec stream, this returns the gem's name.
#
# Example:
#   cat foo.gemspec | gemspec-to-gem-version
#   => foo
#
# These commands are all related:
#   gemspec-cat
#   gemspec-to-gem-description
#   gemspec-to-gem-name
#   gemspec-to-gem-name-version
#   gemspec-to-gem-summary
#   gemspec-to-gem-version
##

grep -m 1 ".description *= *" | sed 's/.*= *"\([^"]*\)".*/\1/'
