#!/bin/sh
set -o errexit

##
# Given a gemspec stream, this returns the gem's summary.
#
# Example:
#   cat foo.gemspec | gemspec-to-gem-summary
#   => "This gem does something nifty."
#
# These commands are all related:
#   gemspec-to-gem-description
#   gemspec-to-gem-name
#   gemspec-to-gem-name-version
#   gemspec-to-gem-summary
#   gemspec-to-gem-version
##

grep -m 1 ".summary *= *" | sed 's/.*= *"\([^"]*\)".*/\1/'
