#!/bin/sh
set -o errexit

##
# Cat the current directory's gemspec file.
#
# Example:
#   cat foo.gemspec | gemspec-to-gem-name-version
#   => foo-1.2.3
#
# These commands are all related:
#   gemspec-cat
#   gemspec-to-gem-description
#   gemspec-to-gem-name
#   gemspec-to-gem-name-version
#   gemspec-to-gem-summary
#   gemspec-to-gem-version
##

cat *.gemspec

